DotNetFundamentalsCore Project/OdeToFood/ViewComponents/RestaurantCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewComponents
{
    /*A View Component in asp.net core derives from a base class which is the view component class
     a view component just like the page model in a razor page can have constructor or i do dependency
      injections
    the difference between razor page and viewcomponent is A viewcompnent doesnt respond to an http request
     A view component is more like a partial view it is going to embedded in some other view that is simply going 
    say please go render this view component so when the rendering happens asp.net core is going to call a method 
    named "Invoke" 
    I have this component "RestaurantCountViewComponent" this service that i can use from a layout view it can do
    its own data access using whatever services it needs it could build its own model and it can render its own view which 
    will plug into the layout view.
     */
    public class RestaurantCountViewComponent : ViewComponent
    {
        private readonly IRestaurantData restaurantData;


        public RestaurantCountViewComponent(IRestaurantData restaurantData)
        {
            this.restaurantData = restaurantData;
        }

        /*One thing about this operation ,this view component if i place it onto the layout page it's going to add
         a query to every page in the app[if you're in a performance sensitive scenario you might want to cache this 
         value]but we are just going to focus on view component
        unlike a page where i can simply say return page to render the associated cshtml file i want to explicitly say i 
        want to return View() so somewhere in the project a view might represent the view for this view component.
        View components works more like a mvc framework inside of the asp.net core 
        you have an action method builds a model and you pass that model to a view by returning some sort of view result
        in a razor page i would simply set that count as a property on my page and then bind to it from the cshtml file.
         */
        public IViewComponentResult Invoke()
        {
            int count = restaurantData.GetCountOfRestaurants();
            return View(count);
        }
    }
}

DotNetFundamentalsCore Project/OdeToFood/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OdeToFood</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />@*Bootsrap css framework*@
    <link rel="stylesheet" href="~/css/site.css" />@*Custom site.css*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">OdeToFood</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Restaurants/List">Restaurants</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            @*Inside of the view we can invoke another method called render section we can have multiple calls here
        each section will have name lets call this one footer section .now we are going to allow pages like
        list details edit to plug content into this section.in the section section we are calling this section is not required
        in other words the list and the dit page they are not required to provide me this section.and the list page wanted to
        render this footer all it needs to define a section using @section
            *@
            @*we just have to pick a location where we want it to render a viewcomponent
        for rendering we can use special tag-helper "<vc-name of the component(kebab case[second capital will become small and -infront of it])> in layout.cs*@
            <vc:restaurant-count></vc:restaurant-count>
            @RenderSection("footer", required: false)
            &copy; 2020 - OdeToFood - <a asp-area="" asp-page="/Privacy">Privacy</a>
            @*The wwwroot Folder in the project serves as the content root for your website so images,css files 
               javascript files all they need to live somewhere inside of wwwroot and if we want to take advantage of features
                like client-side validation using jquery,jquery and other files need to loaded from these folders isnide of wwwroot
                *@
            <img src="~/OdeToFood.png" />
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>@*Script tag to load jquery,bootstrap.js,site.js file*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

@*
Three tips about _Layout 
    1.It doesn not need to live in shared folder
    2.It is not a razor page [A razor page can be called a page where there is @page direcvtive 
    at the beginning of the page]
    3._underscore before the pafe is just an indication this chshtml file render does not exist
    (there is no cshtml.cs page model for this).

    The job of the _Layout is to control the structure of my user interface.
    What are the common elements that need to appear on ever page in user interface ?
    What scripts or css file do i need to include on every page?
    The answer is that type of content goes inside layout.
    There are two valid questions here right now ?
    1.How does a page like restaurant list no where to plug in contenst like this table of restaurants ?
    2.how could that restaurant list page choose a different layout page or not to use this layout page?
    Exactly how did this layout page comes into play


    inside @renderbody the page will render in the layout.

*@